name: BUILD - lint, build and binary upload

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      
    # Install and setup go
    - name: Set up Go 1.14
      uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f # v1
      with:
        go-version: 1.14
      id: go

    # setup gopath
    - name: Set PATH
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    # # install linter
    # - name: install linter
    #   run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0
      
    # checkout relayer
    - name: checkout relayer
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    # setup cache
    - uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # # run linter
    # - name: linter
    #   run: make ci-lint
    
    # build binary
    - name: build binary and move to upload location
      run: make build

    # upload resulting binaries
    - name: upload binaries
      uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1
      with:
        name: rly
        path: ./build/rly
